import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Playfair_Display, Clicker_Script } from 'next/font/google'
import { cn } from '@/shared/lib'
import './globals.css'

const playfairDisplay = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
})

const clickerScript = Clicker_Script({
  variable: '--font-clicker-script',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          `${playfairDisplay.variable} ${clickerScript.variable}`,
          `${playfairDisplay.className} antialiased`,
        )}
      >
        {children}
      </body>
    </html>
  )
}
