import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Playfair_Display, Clicker_Script } from 'next/font/google'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { setRequestLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'

import { routing } from '@/i18n/routing'
import { Layout } from '@/shared/layout'
import { cn } from '@/shared/lib'
import './globals.css'

const playfairDisplay = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
})

const clickerScript = Clicker_Script({
  variable: '--font-clicker-script',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  setRequestLocale(locale)

  return (
    <NextIntlClientProvider>
      <html lang={locale} className='no-scrollbar'>
        <body
          className={cn(
            `${playfairDisplay.variable} ${clickerScript.variable}`,
            `${playfairDisplay.className} antialiased`,
          )}
        >
          <Layout>{children}</Layout>
        </body>
      </html>
    </NextIntlClientProvider>
  )
}

export function generateStaticParams() {
  return routing.locales.map(locale => ({ locale }))
}
